release:
	arm-hisiv500-linux-uclibcgnueabi-gcc -O2 register.c -o register -Wall -static
debug:
	arm-hisiv500-linux-uclibcgnueabi-gcc -O0 -g register.c -o register -Wall -static
clean:
	rm -f register
